name: Test GitOps-ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn joblib jq

      - name: Run training script
        run: |
          python train_model.py

      - name: Show result
        run: |
          cat train_result.json

      - name: Quality Gate (F1 >= 0.8)
        id: quality
        run: |
          VALUE=$(jq .value train_result.json)
          THRESHOLD=0.8

          echo "F1-score obtenu: $VALUE"
          echo "Seuil accepté: $THRESHOLD"

          if (( $(echo "$VALUE < $THRESHOLD" | bc -l) )); then
            echo "Qualité insuffisante ❌"
            exit 1
          fi

          echo "Qualité validée ✅"

      - name: Deploy model to production
        if: success()      # Ne s'exécute que si le Quality Gate est OK
        run: |
          mkdir -p production
          cp models/model.joblib production/model.joblib
          echo "Déploiement réussi : modèle envoyé dans production/"
