name: GitOps MLOps Pipeline

on:
  push:
    branches:
      - main

#Autorise GitHub Actions à modifier le dépôt (pour le git push)
permissions:
  contents: write

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Checkout du repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true 

      # Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # dépendances
      - name: Install dependencies
        run: |
          pip install dvc-gs pandas scikit-learn joblib

      # 4️⃣ Authentification GCP
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          service_account: test-ia@regal-muse-480913-c4.iam.gserviceaccount.com
          project_id: regal-muse-480913-c4
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Récupérer les données
      - name: Pull datasets from DVC
        run: dvc pull

      # Entraîner le modèle candidat
      - name: Train candidate model
        run: |
          python train_model.py --out models/candidate/model.joblib

      # Comparer avec le modèle en production
      - name: Compare with production model
        id: compare
        run: |
          python evaluate.py \
            --candidate models/candidate/metrics.json \
            --production models/production/metrics.json

      # Promotion automatique (LOGIQUE COMPLÈTE)
      - name: Promote model to production
        if: steps.compare.outputs.promote == 'true'
        run: |
          echo "Le nouveau modèle est meilleur — Promotion en cours..."
          
          # Configuration de l'identité Git (obligatoire pour commit)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Création du dossier et copie des fichiers
          mkdir -p models/production
          cp models/candidate/model.joblib models/production/model.joblib
          cp models/candidate/metrics.json models/production/metrics.json

          # Mise à jour de DVC pour le modèle de production
          dvc add models/production/model.joblib
          
          # Push des métadonnées vers Git (.dvc et .json)
          # On ajoute [skip ci] pour éviter de relancer le pipeline en boucle
          git add models/production/model.joblib.dvc models/production/metrics.json
          git commit -m "MLOps: Mise à jour du modèle de production [skip ci]"
          git push origin main

          # Push du modèle physique vers Google Cloud Storage
          dvc push

      # Blocage si échec
      - name: Block deployment
        if: steps.compare.outputs.promote != 'true'
        run: |
          echo "Nouveau modèle moins performant ❌ — Fin du pipeline."
          exit 1